AWSTemplateFormatVersion: "2010-09-09"
Description: "Create EC2 Instance"

Parameters:
  LatestUbuntuFocalAMI:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/canonical/ubuntu/server/focal/stable/current/amd64/hvm/ebs-gp2/ami-id

Resources:  
  MasterEC2: 
    DeletionPolicy: "Delete"
    Type: AWS::EC2::Instance
    Properties: 
      AvailabilityZone: "us-east-1b"
      BlockDeviceMappings: 
      - DeviceName: "/dev/sda1"
        Ebs: 
          VolumeType: "gp2"
          DeleteOnTermination: "true"
          VolumeSize: "30"
          Encrypted: "true"
          KmsKeyId: "a993d3be-913f-4a76-be2e-c5294b39a7b5"
      ImageId: !Ref LatestUbuntuFocalAMI
      InstanceType: "t3.medium"
      KeyName: "bastion_key"
      NetworkInterfaces: 
        - AssociatePublicIpAddress: "true"
          DeleteOnTermination: "true"
          DeviceIndex: "0"
          GroupSet:
            - "sg-0394394f8fa9cf323"
          SubnetId: "subnet-f838619e"
      Tags:
        - Key: "Name"
          Value: "cft-rke-master"

  Worker01EC2: 
    DeletionPolicy: "Delete"
    Type: AWS::EC2::Instance
    Properties: 
      AvailabilityZone: "us-east-1b"
      BlockDeviceMappings: 
      - DeviceName: "/dev/sda1"
        Ebs: 
          VolumeType: "gp2"
          DeleteOnTermination: "true"
          VolumeSize: "30"
          Encrypted: "true"
          KmsKeyId: "a993d3be-913f-4a76-be2e-c5294b39a7b5"
      ImageId: !Ref LatestUbuntuFocalAMI
      InstanceType: "t3.medium"
      KeyName: "bastion_key"
      NetworkInterfaces: 
        - AssociatePublicIpAddress: "true"
          DeleteOnTermination: "true"
          DeviceIndex: "0"
          GroupSet:
            - "sg-0394394f8fa9cf323"
          SubnetId: "subnet-f838619e"
      Tags:
        - Key: "Name"
          Value: "cft-rke-worker01"

  Worker02EC2: 
    DeletionPolicy: "Delete"
    Type: AWS::EC2::Instance
    Properties: 
      AvailabilityZone: "us-east-1b"
      BlockDeviceMappings: 
      - DeviceName: "/dev/sda1"
        Ebs: 
          VolumeType: "gp2"
          DeleteOnTermination: "true"
          VolumeSize: "30"
          Encrypted: "true"
          KmsKeyId: "a993d3be-913f-4a76-be2e-c5294b39a7b5"
      ImageId: !Ref LatestUbuntuFocalAMI
      InstanceType: "t3.medium"
      KeyName: "bastion_key"
      NetworkInterfaces: 
        - AssociatePublicIpAddress: "true"
          DeleteOnTermination: "true"
          DeviceIndex: "0"
          GroupSet:
            - "sg-0394394f8fa9cf323"
          SubnetId: "subnet-f838619e"
      Tags:
        - Key: "Name"
          Value: "cft-rke-worker02"

  Worker03EC2: 
    DeletionPolicy: "Delete"
    Type: AWS::EC2::Instance
    Properties: 
      AvailabilityZone: "us-east-1b"
      BlockDeviceMappings: 
      - DeviceName: "/dev/sda1"
        Ebs: 
          VolumeType: "gp2"
          DeleteOnTermination: "true"
          VolumeSize: "30"
          Encrypted: "true"
          KmsKeyId: "a993d3be-913f-4a76-be2e-c5294b39a7b5"
      ImageId: !Ref LatestUbuntuFocalAMI
      InstanceType: "t3.medium"
      "
      KeyName: "bastion_key"
      NetworkInterfaces: 
        - AssociatePublicIpAddress: "true"
          DeleteOnTermination: "true"
          DeviceIndex: "0"
          GroupSet:
            - "sg-0394394f8fa9cf323"
          SubnetId: "subnet-f838619e"
      Tags:
        - Key: "Name"
          Value: "cft-rke-worker03"                  
Outputs:
  MasterPublicIP:
    Description: Public IP Address of ec2 instance
    Value:
      Fn::GetAtt:
        - MasterEC2
        - PublicIp
  MasterPrivateIP:
    Description: Private IP Address of ec2 instance
    Value:
      Fn::GetAtt:
        - MasterEC2
        - PrivateIp
  Worker01PrivateIP:
    Description: Private IP Address of ec2 instance
    Value:
      Fn::GetAtt:
        - Worker01EC2
        - PrivateIp
  Worker02PrivateIP:
    Description: Private IP Address of ec2 instance
    Value:
      Fn::GetAtt:
        - Worker02EC2
        - PrivateIp
  Worker03PrivateIP:
    Description: Private IP Address of ec2 instance
    Value:
      Fn::GetAtt:
        - Worker03EC2
        - PrivateIp
